<template>
	<view class="page">
		<view class="header"><text class="back" @tap="back">‹</text><view><text class="title">{{ remote ? '异地投喂' : '情侣共同点餐' }}</text><text class="subtitle">按分类选菜，双方都能在订单里查看</text></view></view>
		<scroll-view class="category-bar" scroll-x show-scrollbar="false"><view class="category-list"><view class="chip" :class="{active:activeCategoryId===''}" @tap="activeCategoryId=''">全部</view><view class="chip" :class="{active:String(activeCategoryId)===String(cat.id)}" v-for="cat in categories" :key="cat.id" @tap="activeCategoryId=cat.id">{{cat.catName}}</view></view></scroll-view>
		<scroll-view class="dish-scroll" scroll-y>
			<view class="dish-list" v-if="filteredDishes.length"><view class="dish" v-for="dish in filteredDishes" :key="dish.id"><image :src="dish.cover||'/static/onion_chicken.png'" mode="aspectFill"/><view class="dish-copy"><text class="dish-name">{{dish.dishName}}</text><text class="dish-desc">{{dish.description||'家常好味，适合一起分享'}}</text><text class="price">￥{{dish.virtualPrice||0}}</text></view><view class="qty"><text v-if="quantity(dish.id)" @tap="change(dish.id,-1)">−</text><text v-if="quantity(dish.id)" class="number">{{quantity(dish.id)}}</text><text @tap="change(dish.id,1)">＋</text></view></view></view>
			<view class="empty" v-else>该分类暂时没有菜品</view><view class="safe-space"></view>
		</scroll-view>
		<view class="bottom"><view><text>已选 {{totalCount}} 份</text><text class="total">￥{{totalAmount}}</text></view><view class="confirm" :class="{disabled:!totalCount}" @tap="confirm">去确认订单</view></view>
	</view>
</template>
<script>
	import { apiCategoryTree } from '@/api/category.js'
	import { apiDishList } from '@/api/dish.js'
	export default { data(){return{remote:false,categories:[],dishes:[],activeCategoryId:'',quantities:{}}},computed:{filteredDishes(){if(this.activeCategoryId==='')return this.dishes;return this.dishes.filter(d=>String(d.categoryId)===String(this.activeCategoryId))},totalCount(){return Object.values(this.quantities).reduce((s,n)=>s+Number(n||0),0)},totalAmount(){const value=this.dishes.reduce((sum,d)=>sum+Number(d.virtualPrice||0)*this.quantity(d.id),0);return value.toFixed(2)}},onLoad(o){this.remote=String(o.remote||'')==='1';this.load()},methods:{async load(){try{const [catRes,dishRes]=await Promise.all([apiCategoryTree(),apiDishList({pageNum:1,pageSize:100})]);const flatten=rows=>(rows||[]).reduce((all,item)=>all.concat(item,flatten(item.children)),[]);this.categories=flatten((catRes&&catRes.data)||[]);this.dishes=(dishRes&&dishRes.rows)||[]}catch(e){}},quantity(id){return Number(this.quantities[String(id)]||0)},change(id,delta){const key=String(id),next=Math.max(0,Math.min(99,this.quantity(id)+delta));this.$set?this.$set(this.quantities,key,next):(this.quantities[key]=next)},confirm(){if(!this.totalCount){uni.showToast({title:'请先选择菜品',icon:'none'});return}const items=this.dishes.filter(d=>this.quantity(d.id)>0).map(d=>({dishId:d.id,quantity:this.quantity(d.id)}));const encoded=encodeURIComponent(JSON.stringify(items));uni.navigateTo({url:`/pages/submit-order/submit-order?coupleOrder=1&remote=${this.remote?'1':'0'}&items=${encoded}`})},back(){uni.navigateBack()}}}
</script>
<style>
	.page{min-height:100vh;background:#f4faf7;color:#1f2926}.header{height:190rpx;padding:calc(44rpx + env(safe-area-inset-top)) 28rpx 24rpx;display:flex;align-items:flex-end;background:linear-gradient(145deg,#28cfa3,#77dfbf);color:#f8fffc;box-sizing:border-box}.back{width:66rpx;font-size:54rpx}.header>view{display:flex;flex-direction:column}.title{font-size:38rpx;font-weight:900}.subtitle{margin-top:8rpx;font-size:22rpx;opacity:.85}.category-bar{height:96rpx;background:#f8fffc;white-space:nowrap}.category-list{height:96rpx;padding:0 24rpx;display:inline-flex;align-items:center;gap:14rpx}.chip{height:58rpx;padding:0 25rpx;display:flex;align-items:center;border-radius:30rpx;background:#eaf2ef;color:#61706b;font-size:24rpx;font-weight:800}.chip.active{background:#30cda3;color:#f8fffc}.dish-scroll{height:calc(100vh - 398rpx - env(safe-area-inset-bottom))}.dish-list{padding:18rpx 24rpx}.dish{min-height:154rpx;margin-bottom:16rpx;padding:16rpx;display:flex;align-items:center;border-radius:22rpx;background:#fbfefd}.dish image{width:126rpx;height:126rpx;border-radius:17rpx}.dish-copy{flex:1;min-width:0;margin-left:18rpx;display:flex;flex-direction:column}.dish-name{font-size:29rpx;font-weight:900}.dish-desc{margin-top:8rpx;color:#8a9792;font-size:21rpx;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.price{margin-top:14rpx;color:#24b98f;font-size:27rpx;font-weight:900}.qty{display:flex;align-items:center;gap:10rpx}.qty>text:not(.number){width:48rpx;height:48rpx;border-radius:50%;background:#30cda3;color:#f8fffc;text-align:center;line-height:46rpx;font-weight:900}.number{min-width:28rpx;text-align:center;font-weight:900}.empty{padding:100rpx 20rpx;text-align:center;color:#8b9893}.safe-space{height:30rpx}.bottom{position:fixed;left:0;right:0;bottom:0;height:calc(112rpx + env(safe-area-inset-bottom));padding:0 24rpx env(safe-area-inset-bottom);display:flex;align-items:center;justify-content:space-between;background:#fbfefd;box-sizing:border-box}.bottom>view:first-child{display:flex;flex-direction:column;color:#71807a;font-size:22rpx}.total{margin-top:5rpx;color:#1f2926;font-size:30rpx;font-weight:900}.confirm{width:260rpx;height:74rpx;border-radius:38rpx;background:#30cda3;color:#f8fffc;display:flex;align-items:center;justify-content:center;font-size:28rpx;font-weight:900}.confirm.disabled{opacity:.45}
</style>
